### ISSUE TITLE
No Image Layer loading in the map

### ISSUE THREAD

**Issue by esyasi** [tethysplatform/tethysapp-earth_engine#2]
Hi,

The image layer is not being loaded. I have followed creating and registering service account. I am not getting any error but the images are not rendered. I have also changed the version of earthengine-api=0.1.269. Could you point me to possible source of error.

**Comment by swainn** [comment]
Hi @esyasi, It should work with the latest version of the earthengine-api. The constraint for version 0.1.269 was for an older version of the tutorial. Try updating to the latest version. 

Also, could you provide answers to these questions:

Which step of the tutorial are you on when you experience errors?
Have you tried cloning the solution to see if it works?
Are there any errors in the JavaScript console in your web browser?

**Comment by esyasi** [comment]
Hi, Thanks for the comments. Here are the updates:

1. I have using the latest updated api version which is 0.1.270.
2. I have encountered no error until "[[Add Map View Section](https://docs.tethysplatform.org/en/3.0.5/tutorials/google_earth_engine/map_view.html)]". I can also see the responses in console log. Basemap too loads fine. 
3. In visualize Google Earth Engine dataset section, after implementing all the steps, when i load the app and try loading map, the loading gif appears and vanishes, but no dataset is rendered. 
4. I have cloned the repository and tried again. It's not working as there is no response from the server.
5. There is error in Javascript console (Image attached).

The error might be due to GEE service account.  I have done the following:

1. Created a service account in a cloud project.
2. Registered the service account.
3. Generated JSON key.
4. Updated params.py with service account name and key path. 

Is there anything else that I am missing or doing wrong? Is there some permission setting that I need to do in service account?
<img width="642" alt="Screenshot 2021-06-17 at 12 06 37 PM" src="https://user-images.githubusercontent.com/42907143/122345293-55057680-cf65-11eb-8d11-2744f89b9023.png">

**Comment by esyasi** [comment]
Also, from the Terminal, I can access the Earth Engine API without any error

<img width="1078" alt="Screenshot 2021-06-17 at 3 44 47 PM" src="https://user-images.githubusercontent.com/42907143/122377968-2ac2b180-cf83-11eb-838d-778c6253966b.png">

**Comment by esyasi** [comment]
Resolved. Thanks!

**Comment by swainn** [comment]
Sorry, @esyasi for the delay. What was the issue?

I was going to say that 404 errors usually are caused by accessing a resource that doesn't exist. Often this happens when you have a typo in the name of the dataset.

Also, after creating a service account, you need to register it with Google Earth Engine as described here: https://developers.google.com/earth-engine/guides/service_account#register-the-service-account-to-use-earth-engine

**Comment by esyasi** [comment]
Hi, Yes, it was some conflict with service account. I created a new service account and key and registered it with GEE. Then, I got valid response from server.
